export const PURGE_EXPIRED_CONTENTS = 'PURGE_EXPIRED_CONTENTS';
export const SET_CACHE_KEY = 'SET_CACHE_KEY';
export const SET_CACHE_ITEMS = 'SET_CACHE_ITEMS';
export const SET_CACHED_IMAGE_URI = 'SET_CACHED_IMAGE_URI';
