export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_CURRENT_CART = 'SET_CURRENT_CART';
export const SET_CURRENT_CART_ID_CUSTOMER = 'SET_CURRENT_CART_ID_CUSTOMER';
export const SET_PRODUCT_CART_ITEM_QUANTITY = 'SET_PRODUCT_CART_ITEM_QUANTITY';
export const EMPTY_CART = 'EMPTY_CART';
export const BACKORDER = 'BACKORDER';
export const SET_SELECTED_SHIPPING_ADDRESS_ID =
    'SET_SELECTED_SHIPPING_ADDRESS_ID';
export const SET_SELECTED_BILLING_ADDRESS_ID =
    'SET_SELECTED_BILLING_ADDRESS_ID';
export const SHOW_SHIPPING_ADDRESS_FORM = 'SHOW_SHIPPING_ADDRESS_FORM';
export const SHOW_BILLING_ADDRESS_FORM = 'SHOW_BILLING_ADDRESS_FORM';
