export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_CURRENT_CART = 'SET_CURRENT_CART';
export const SET_CURRENT_CART_ID_CUSTOMER = 'SET_CURRENT_CART_ID_CUSTOMER';
export const SET_PRODUCT_CART_ITEM_QUANTITY = 'SET_PRODUCT_CART_ITEM_QUANTITY';
export const EMPTY_CART = 'EMPTY_CART';
