export const GET_CATEGORY = 'GET_CATEGORY';
export const SET_CATEGORIES_ITEMS = 'SET_CATEGORIES_ITEMS';
export const GET_MAIN_SECTIONS = 'GET_MAIN_SECTIONS';
export const GET_MISSING_CATEGORIES = 'GET_MISSING_CATEGORIES';
