export const REGISTER_EMAIL_ERROR = 'REGISTER_EMAIL_ERROR';
export const REGISTER_FIRSTNAME_ERROR = 'REGISTER_FIRSTNAME_ERROR';
export const REGISTER_LASTNAME_ERROR = 'REGISTER_LASTNAME_ERROR';
export const REGISTER_PASSWORD_ERROR = 'REGISTER_PASSWORD_ERROR';
export const REGISTER_NEWSLETTER_ERROR = 'REGISTER_NEWSLETTER_ERROR';
export const REGISTER_PSGDPR_ERROR = 'REGISTER_PSGDPR_ERROR';

export const LOGIN_EMAIL_ERROR = 'LOGIN_EMAIL_ERROR';
export const LOGIN_PASSWORD_ERROR = 'LOGIN_PASSWORD_ERROR';

export const ADDRESS_ALIAS_ERROR = 'ADDRESS_ALIAS_ERROR';
export const ADDRESS_FIRSTNAME_ERROR = 'ADDRESS_FIRSTNAME_ERROR';
export const ADDRESS_LASTNAME_ERROR = 'ADDRESS_LASTNAME_ERROR';
export const ADDRESS_COMPANY_ERROR = 'ADDRESS_COMPANY_ERROR';
export const ADDRESS_VAT_NUMBER_ERROR = 'ADDRESS_VAT_NUMBER_ERROR';
export const ADDRESS_ADDRESS1_ERROR = 'ADDRESS_ADDRESS1_ERROR';
export const ADDRESS_ADDRESS2_ERROR = 'ADDRESS_ADDRESS2_ERROR';
export const ADDRESS_POSTCODE_ERROR = 'ADDRESS_POSTCODE_ERROR';
export const ADDRESS_ID_STATE_ERROR = 'ADDRESS_ID_STATE_ERROR';
export const ADDRESS_ID_COUNTRY_ERROR = 'ADDRESS_ID_COUNTRY_ERROR';
export const ADDRESS_CITY_ERROR = 'ADDRESS_CITY_ERROR';
export const ADDRESS_PHONE_ERROR = 'ADDRESS_PHONE_ERROR';

export const SET_ERROR = 'SET_ERROR';
export const SET_ERRORS = 'SET_ERRORS';
