export const REGISTER_EMAIL_ERROR = 'REGISTER_EMAIL_ERROR';
export const REGISTER_FIRSTNAME_ERROR = 'REGISTER_FIRSTNAME_ERROR';
export const REGISTER_LASTNAME_ERROR = 'REGISTER_LASTNAME_ERROR';
export const REGISTER_PASSWORD_ERROR = 'REGISTER_PASSWORD_ERROR';
export const REGISTER_NEWSLETTER_ERROR = 'REGISTER_NEWSLETTER_ERROR';
export const REGISTER_PSGDPR_ERROR = 'REGISTER_PSGDPR_ERROR';

export const LOGIN_EMAIL_ERROR = 'LOGIN_EMAIL_ERROR';
export const LOGIN_PASSWORD_ERROR = 'LOGIN_PASSWORD_ERROR';

export const SET_ERROR = 'SET_ERROR';
export const SET_ERRORS = 'SET_ERRORS';
