export const GET_ORDERS = 'GET_ORDERS';
export const GET_MISSING_ORDERS = 'GET_MISSING_ORDERS';
export const SET_ORDERS_ITEMS = 'SET_ORDERS_ITEMS';
export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const SET_SELECTED_PAYMENT_METHOD = 'SET_SELECTED_PAYMENT_METHOD';
