export const GET_PRODUCT = 'GET_PRODUCT';
export const SET_PRODUCTS_ITEMS = 'SET_PRODUCTS_ITEMS';
export const GET_MISSING_PRODUCTS = 'GET_MISSING_PRODUCTS';
export const GET_PRODUCT_IMAGES = 'GET_PRODUCT_IMAGES';
