export const GET_PRODUCT = 'GET_PRODUCT';
export const SET_PRODUCTS_ITEMS = 'SET_PRODUCTS_ITEMS';
export const SET_PRODUCTS_SPECIFIC_PRICES = 'SET_PRODUCTS_SPECIFIC_PRICES';
export const SET_PRODUCTS_STOCK_AVAILABILITIES =
    'SET_PRODUCTS_STOCK_AVAILABILITIES';
export const GET_MISSING_PRODUCTS = 'GET_MISSING_PRODUCTS';
export const GET_PRODUCT_IMAGES = 'GET_PRODUCT_IMAGES';
export const GET_MISSING_PRICES = 'GET_MISSING_PRICES';
export const GET_MISSING_STOCK_AVAILABILITY = 'GET_MISSING_STOCK_AVAILABILITY';
