export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_SEARCH_SELECTED_CATEGORY_ID =
    'SET_SEARCH_SELECTED_CATEGORY_ID';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
